- id: REQ-1
  name: 车票查询与展示
  description: |
    用户在该模块输入行程基本信息（出发/到达地、日期、票种、往返类型），
    系统根据输入条件从后端 API 获取车次数据，并提供筛选、排序和展示功能，
    用户可以直接点击“预订”进入购票流程。

- id: REQ-2
  name: 用户认证与个人中心
  description: |
    包含用户注册、登录、退出、找回密码以及个人信息查看与修改功能，
    支持用户名/手机号/邮箱登录和个人中心信息管理。

- id: REQ-3
  name: 订单系统
  description: |
    覆盖从确认购票意向开始，到订单创建、支付、查询、改签、退票的
    全生命周期订单管理流程。

- id: REQ-4
  name: 乘客管理系统
  description: |
    允许用户管理常用乘车人信息，包括查看、新增、修改和删除操作，
    支持敏感数据脱敏展示和基础校验逻辑。

