- id: REQ-1
  name: 车票查询与展示
  description: |
    用户在该模块输入行程基本信息（出发/到达地、日期、票种、往返类型），系统根据输入条件从后端 API 获取车次数据，
    并提供实时筛选、排序和展示功能。用户可以直接点击“预订”进入购票流程。

    UI 概要：
    - 参考图片路径: requirements/assets/1.车票查询与展示/1.png
    - 整体页面采用 12306 经典蓝白配色。
    - 顶部导航栏：显示登录状态及个人中心入口。
    - 搜索区域：蓝色背景面板，包含双行输入结构。
    - 日期切换栏：在结果上方，展示 15 天的滑动页签，当前选中日期高亮。
    - 筛选区域：白色背景卡片，默认收起，展开后展示所有筛选维度（发车时间、车次类型、车站、席别）。
    - 结果列表：宽屏表格（约 1200px），包含车次、车站、历时、票价及余票等信息，支持表头点击排序。
    详细需求参见 docs/requirements/1.车票查询与展示.yaml。

  scenarios:
    - name: 完整购票查询流程
      steps:
        - action: 在“出发地”输入“北京”，在“目的地”输入“上海”
          expectation: 两个城市名正确显示。
        - action: 选择出发日期为“2025-12-30”
          expectation: 日历框关闭，输入框显示选中日期。
        - action: 点击“查询”按钮
          expectation: 后端搜索 API 被调用，下方列表显示对应的车次结果（如 G21, G101 等）。

- id: REQ-2
  name: 用户认证与个人中心
  description: |
    覆盖登录、注册、退出、找回密码以及个人信息查看与编辑等功能。
    详细需求参见 docs/requirements/2.用户认证与个人中心.yaml。

- id: REQ-3
  name: 订单系统
  description: |
    负责创建订单、支付（模拟）、取消、退票以及订单查询等业务流程。
    详细需求参见 docs/requirements/3.订单系统.yaml。

- id: REQ-4
  name: 乘客管理
  description: |
    管理常用乘客信息，包括新增、编辑、删除和列表展示等功能。
    详细需求参见 docs/requirements/4.乘客管理.yaml。

- id: REQ-5
  name: 系统集成与一致性
  description: |
    规范跨模块的路由跳转、乘车人与用户信息集成、订单与用户隔离，以及车次时间在订单创建、支付、详情中的端到端同步。
    同时对前端 E2E 测试与后端集成测试提出覆盖要求，确保集成功能可通过自动化测试验证。
    详细需求参见 docs/requirements/5.系统集成与一致性.yaml。
