"""Initial migration

Revision ID: 2a6f3ecf7d3b
Revises: 
Create Date: 2026-01-19 14:03:49.517275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a6f3ecf7d3b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stations',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('pinyin', sa.String(length=100), nullable=True),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('is_hot', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_stations_city'), 'stations', ['city'], unique=False)
    op.create_index(op.f('ix_stations_id'), 'stations', ['id'], unique=False)
    op.create_index(op.f('ix_stations_name'), 'stations', ['name'], unique=True)
    op.create_table('users',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('trains',
    sa.Column('train_number', sa.String(), nullable=False),
    sa.Column('train_type', sa.Enum('G', 'D', 'Z', name='train_type'), nullable=False),
    sa.Column('from_station_id', sa.Integer(), nullable=False),
    sa.Column('to_station_id', sa.Integer(), nullable=False),
    sa.Column('departure_time', sa.Time(), nullable=False),
    sa.Column('arrival_time', sa.Time(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('arrival_day_offset', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['from_station_id'], ['stations.id'], ),
    sa.ForeignKeyConstraint(['to_station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trains_from_station_id'), 'trains', ['from_station_id'], unique=False)
    op.create_index(op.f('ix_trains_id'), 'trains', ['id'], unique=False)
    op.create_index(op.f('ix_trains_to_station_id'), 'trains', ['to_station_id'], unique=False)
    op.create_index(op.f('ix_trains_train_number'), 'trains', ['train_number'], unique=True)
    op.create_table('orders',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('train_id', sa.Integer(), nullable=False),
    sa.Column('departure_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'CANCELLED', 'REFUNDED', 'PARTIAL_REFUNDED', 'COMPLETED', name='order_status'), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['train_id'], ['trains.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_train_id'), 'orders', ['train_id'], unique=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_table('seats',
    sa.Column('train_id', sa.Integer(), nullable=False),
    sa.Column('travel_date', sa.Date(), nullable=False),
    sa.Column('seat_type', sa.Enum('FIRST_CLASS', 'SECOND_CLASS', 'SOFT_SLEEPER', 'HARD_SLEEPER', name='seat_type'), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('available', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['train_id'], ['trains.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('train_id', 'travel_date', 'seat_type', name='uq_seat_train_date_type')
    )
    op.create_index(op.f('ix_seats_id'), 'seats', ['id'], unique=False)
    op.create_index(op.f('ix_seats_train_id'), 'seats', ['train_id'], unique=False)
    op.create_table('order_items',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('passenger_name', sa.String(length=100), nullable=False),
    sa.Column('passenger_id_card', sa.String(length=50), nullable=False),
    sa.Column('seat_type', sa.Enum('FIRST_CLASS', 'SECOND_CLASS', 'SOFT_SLEEPER', 'HARD_SLEEPER', name='seat_type'), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('seat_number', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'CANCELLED', 'REFUNDED', 'PARTIAL_REFUNDED', 'COMPLETED', name='order_item_status'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_id'), 'order_items', ['id'], unique=False)
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_seats_train_id'), table_name='seats')
    op.drop_index(op.f('ix_seats_id'), table_name='seats')
    op.drop_table('seats')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_train_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_trains_train_number'), table_name='trains')
    op.drop_index(op.f('ix_trains_to_station_id'), table_name='trains')
    op.drop_index(op.f('ix_trains_id'), table_name='trains')
    op.drop_index(op.f('ix_trains_from_station_id'), table_name='trains')
    op.drop_table('trains')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_stations_name'), table_name='stations')
    op.drop_index(op.f('ix_stations_id'), table_name='stations')
    op.drop_index(op.f('ix_stations_city'), table_name='stations')
    op.drop_table('stations')
    # ### end Alembic commands ###
