"""add passengers table

Revision ID: 7ef33fa8dcd4
Revises: 0001_req1_core_tables
Create Date: 2026-01-19 20:24:15.548697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7ef33fa8dcd4'
down_revision: Union[str, None] = '0001_req1_core_tables'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("TRUNCATE TABLE passengers CASCADE")
    op.add_column('passengers', sa.Column('id_card', sa.String(length=30), nullable=False))
    op.add_column('passengers', sa.Column('type', sa.SmallInteger(), nullable=False))
    op.add_column('passengers', sa.Column('verify_status', sa.SmallInteger(), nullable=False))
    op.alter_column('passengers', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('passengers', 'id_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.SmallInteger(),
               existing_nullable=False,
               postgresql_using='id_type::integer')
    op.drop_index('ix_passengers_user_id', table_name='passengers')
    op.drop_constraint('uq_passenger_user_id_id_type_id_number', 'passengers', type_='unique')
    op.create_unique_constraint('uq_user_id_card', 'passengers', ['user_id', 'id_type', 'id_card'])
    op.drop_column('passengers', 'passenger_type')
    op.drop_column('passengers', 'created_at')
    op.drop_column('passengers', 'status')
    op.drop_column('passengers', 'id_number')
    op.drop_column('passengers', 'has_orders')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('passengers', sa.Column('has_orders', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('passengers', sa.Column('id_number', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.add_column('passengers', sa.Column('status', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('passengers', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('passengers', sa.Column('passenger_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_constraint('uq_user_id_card', 'passengers', type_='unique')
    op.create_unique_constraint('uq_passenger_user_id_id_type_id_number', 'passengers', ['user_id', 'id_type', 'id_number'])
    op.create_index('ix_passengers_user_id', 'passengers', ['user_id'], unique=False)
    op.alter_column('passengers', 'id_type',
               existing_type=sa.SmallInteger(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('passengers', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('passengers', 'verify_status')
    op.drop_column('passengers', 'type')
    op.drop_column('passengers', 'id_card')
    # ### end Alembic commands ###
