"""add_timestamps_to_passenger

Revision ID: d90414145995
Revises: 7ef33fa8dcd4
Create Date: 2026-01-19 20:43:49.016673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd90414145995'
down_revision: Union[str, None] = '7ef33fa8dcd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('passengers', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('passengers', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('passengers', 'updated_at')
    op.drop_column('passengers', 'created_at')
    # ### end Alembic commands ###
